### ISSUE TITLE
Ignore, this was a user error by me :(

### ISSUE THREAD

**Issue by GroxicTinch** [BetterDiscord/Installer#184]
**Describe the bug**
Using a batch file or CMD to change the APPDATA env variable and location of where discord saves settings used to work for BetterDiscord as well and now only kind of works. If the appropriate BD files are put into the default %appdata% then the program runs fine and uses the altered location to save settings but running with all files in the altered location returns an Uncaught Exception.

`A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot find module 'C:\Users\USERNAME\AppData\Roaming\BetterDiscord\data\betterdiscord.asar'
Require stack:
- Z:\Program Files\Discord\Discord\app-1.0.9002\resources\app\index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (Z:\Program Files\Discord\Discord\app-1.0.9002\resources\app\index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)`

`Z:\Program Files\Discord\Discord\Profile\AppData\Roaming` being the altered location

**To Reproduce**
1. Install BetterDiscord
2. Move C:\Users\USERNAME\AppData\Roaming\BetterDiscord to a new location e.g. c:\FakeRoaming\BetterDiscord
3. Open CMD and use `set APPDATA=c:\FakeRoaming`
4. Navigate to discord using the same CMD and run
5. See Error message.

**Expected behavior**
The module should be looking at `Z:\Program Files\Discord\Discord\Profile\AppData\Roaming\BetterDiscord\data\betterdiscord.asar` but is instead looking at 'C:\Users\USERNAME\AppData\Roaming\BetterDiscord\data\betterdiscord.asar'

**System Information:**
 - OS: Windows 10
- Discord Version: Stable

**Additional context**

**Comment by GroxicTinch** [comment]
Sorry I just went through and tried everything again on a new device, apparently my current computer the install was getting an old version of discord that was in an adjacent folder. Sorry for the false issue.
